Alternate feature branch
Kasuhira/New-York-Times-Clone pull request #1
Opened 2019-12-02 21:11 UTC by Kasuhira

Finished New York Times project

2019-12-02 22:54 UTC, pelzolga123 requested changes
Project requires changes.

2019-12-02 22:54 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!
But there are few things that need to be corrected:
#### General
* [ ] check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project.
* [ ] README.md file is not descriptive.
* [ ] Stickler errors should be fixed.
* [ ] Id should be unique for each element. (You have same id `first-line` for multiple elements. Better use class instead.)

#### Navigation bar
* [ ] The NY Times logo should be a link
#### Bottom part
* [ ] It should contain links to other articles with image previews on the leftmost side. (Right now you have `p` tags there, but they need to be links). 
#### Footer
* [ ] It should have a fixed position (it sticks to the bottom part of the screen) 
Like on original website:
![image](https://user-images.githubusercontent.com/20416431/69982065-4189ea80-153c-11ea-9a36-1bbab7eff1a7.png)

 #### Main content
* [ ] 'Theory of inflation' part is missing.
![image](https://user-images.githubusercontent.com/20416431/70001054-fcc67980-1564-11ea-9a6c-77d7df56fd73.png)
* [ ] 'Read more' button is not needed, please do the whole page instead.
![image](https://user-images.githubusercontent.com/20416431/70001153-3a2b0700-1565-11ea-84b9-28f7b6f856c1.png)

###  Please kindly make this changes and send another code review request.

If you have any questions or need help, you can message me on slack. *Happy coding*

2019-12-03 18:46 UTC, mosesogwo requested changes
## :clap: Well done guys
### Only one more requirement left for you to :airplane: 

You have used a table to align items in the **theory of inflation** section. You are required to use float to align all items in this project. (See project specific section on pathwright).

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/float_requirement.png)

You're almost there. Keep the good work up.

**Status: Changes required**

2019-12-03 18:46 UTC, mosesogwo commented on index.html
> +                </table>
All elements should be aligned using float.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/float_requirement.png)

2019-12-03 22:08 UTC, nikasulo approved these changes
# Congratulations :tada: you may merge!
You did such a great job implementing the requested changes :smile: please keep the energy moving forward :+1: . See you at the top :rocket:.

2019-12-03 22:19 UTC, merged